#!/usr/bin/env python3
"""Generate combined/deltas.inc from delta name table.

Output: .equ DELTA_IDX_X / .equ DELTA_OFF_X for each entry.
DELTA_OFF_X = 8 + idx*4 (anchor magic 8B + idx-th 4B slot).
"""

import os
import sys

# Phase 1 deltas only. Later phases append.
DELTAS = [
    ('REG_ALIAS_MAP', 0),
    ('ALIAS_MAP', 1),
    ('PAYLOAD_START', 2),
    ('PAYLOAD_END', 3),
    ('NOP_SLOT_0', 4),
    ('NOP_SLOT_1', 5),
    ('NOP_SLOT_2', 6),
    ('NOP_SLOT_3', 7),
    ('NOP_SLOT_4', 8),
    ('NOP_SLOT_5', 9),
    ('NOP_SLOT_6', 10),
    ('NOP_SLOT_7', 11),
    ('NOP_SLOT_8', 12),
    ('NOP_SLOT_9', 13),
    ('NOP_SLOT_10', 14),
    ('NOP_SLOT_11', 15),
    ('JUNK_TEMPLATES', 16),
    ('FORMAT_PERM', 17),
    ('FORMAT_DISPATCH', 18),
    ('SWAP_SITE_TABLE', 19),
    ('REORDER_TABLE', 20),
    ('INIT_OP_TABLE', 21),
]


def main():
    out_path = os.path.join(os.path.dirname(__file__), 'deltas.inc')
    max_off = 8 + max(idx for _, idx in DELTAS) * 4
    if max_off > 127:
        sys.stderr.write(f"WARN: max DELTA_OFF = {max_off}, exceeds imm8 range. "
                         f"Some ADD_REG_IMM8 may need ADD_REG_IMM32 fallback.\n")

    with open(out_path, 'w') as f:
        f.write("# AUTOGENERATED by combined/gen_deltas.py — do not edit.\n")
        f.write("# Defines DELTA_IDX_X and DELTA_OFF_X for delta_table entries.\n\n")
        for name, idx in DELTAS:
            f.write(f".equ DELTA_IDX_{name}, {idx}\n")
            f.write(f".equ DELTA_OFF_{name}, {8 + idx * 4}\n")
    print(f"Wrote {out_path} ({len(DELTAS)} entries)")


if __name__ == '__main__':
    main()
